<?php

/**
 * Implementation of hook_menu for settings page
 */
function uservoice_menu() {
  $items = array();
  $items['admin/config/uservoice'] = array(
    'title'            => 'UserVoice settings',
    'description'      => 'Administer UserVoice settings',
    'page callback'    => 'drupal_get_form',
    'page arguments'   => array('uservoice_settings'),
    'access arguments' => array('administer site configuration'),
    'file'             => 'uservoice.admin.inc',
  );
  return $items;
}

/**
 * Implements hook_init().
 */
function uservoice_init() {
  _uservoice_check_api_key();
  if (!path_is_admin(current_path())) {
    _uservoice_include_misc();
  }
}

/**
 * Include uservoice JS SDk, settings
 */
function _uservoice_include_misc() {
  $keys = array(
    'api_key',
    'accent_color',
    'trigger_color',
    'trigger_background_color',
    'trigger_style',
    'trigger_position',
    'mode',
    'locale'
  );
  foreach ($keys as $name) {
    $settings[$key] = variable_get('uservoice_'. $name, NULL);
  }
  $settings['locale'] = drupal_strtolower($settings['locale']);
  drupal_add_js(drupal_get_path('module', 'uservoice'). '/js/uservoice.js');
  drupal_add_js(array('UserVoice' => $settings), 'setting');  
}

/**
 * Check if uservoice api key has been setup
 */
function _uservoice_check_api_key() {
  if (!variable_get('uservoice_api_key', NULL)) {
    $msg = t('UserVoice setup is not complete. Go to !link and add your API Key.', 
      array('!link' => l('The settings page', 'admin/config/uservoice'))
    );
    drupal_set_message($msg, 'error');
  }
}